font_family     Iosevka Nerd Font
font_size 		18.0
bold_font       auto
italic_font      auto
bold_italic_font auto

background_opacity 1.0
confirm_os_window_close 0

map ctrl+shift+n new_os_window_with_cwd

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

selection_foreground none
selection_background none

window_padding_width 4

foreground #dddddd
background #0f0f0f
cursor #dddddd
